projects:
  - name: application
    applications:
      - name: application
        namespace: argocd
        source:
          path: GitOps/charts
          repoURL: https://github.com/Junho-06/MSA-Architecture-Practice.git
        syncPolicy:
          automated:
            prune: true
            selfHeal: true