{{- range .Values.project }}
{{- $envname := .name }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: {{ $envname }}
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get"]
  resourceNames:
  {{- range .projects }}
    - {{ . }}
  {{- end }}
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $envname }}-{{ . }}
  namespace: default
subjects:
- kind: User 
  name: {{ . }}
roleRef:
  kind: Role
  name: {{ $envname }}
  apiGroup: rbac.authorization.k8s.io