apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istiocontrolplane
  namespace: istio-system
spec:
  profile: {{ .Values.istioOperator.profile }}
  meshConfig:
    accessLogFile: /dev/stdout
  components:
    pilot:
      k8s:
        {{- with .Values.nodeSelector }}
        nodeSelector: {{ toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.tolerations }}
        tolerations: {{ toYaml . | nindent 10 }}
        {{- end }}
    ingressGateways:
      - name: istio-ingressgateway
        namespace: istio-system
        enabled: true
        label:
          service.istio.io/canonical-name: istio-ingressgateway
        k8s:
          service:
            externalTrafficPolicy: {{ .Values.istioOperator.service.externalTrafficPolicy }}
          hpaSpec:
            minReplicas: {{ .Values.istioOperator.hpaSpec.minReplicas }}
            maxReplicas: {{ .Values.istioOperator.hpaSpec.maxReplicas }}
          {{- with .Values.nodeSelector }}
          nodeSelector: {{ toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.tolerations }}
          tolerations: {{ toYaml . | nindent 12 }}
          {{- end }}
          service:
            type: LoadBalancer
            ports:
            {{- range .Values.istioOperator.servicePorts }}
            - name: {{ .name }}
              port: {{ .port }}
              targetPort: {{ .targetPort }}
            {{- end }}
          {{- with .Values.istioOperator.serviceAnnotations }}
          serviceAnnotations: {{ toYaml . | nindent 12 }}
          {{- end }}
  values:
    sidecarInjectorWebhook:
      rewriteAppHTTPProbe: true
    gateways:
      istio-ingressgateway:
        type: ClusterIP
    global:
      {{- with .Values.nodeSelector }}
      defaultNodeSelector: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      defaultTolerations: {{ toYaml . | nindent 8 }}
      {{- end }}
  unvalidatedValues:
    {{- with .Values.nodeSelector }}
    nodeSelector: {{ toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.tolerations }}
    tolerations: {{ toYaml . | nindent 6 }}
    {{- end }}