name: Spring CI

on:
  push:
    paths:
      - "Spring/**"
    branches: [ "main" ]

  workflow_dispatch:
    
permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working_directory: ./Spring

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Grant execute permission for gradlew & Build with Gradle
      run: |
        cd ${{ env.working_directory }}
        chmod +x ./gradlew
        ./gradlew clean build

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
  
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
  
    - name: Build, tag, and push docker image to Amazon ECR
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        REPOSITORY: msa_ecr_spring_registry
        IMAGE_TAG: ${{ github.sha }}
      run: |
        cd ${{ env.working_directory }}
        docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
        docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG