name: Spring CI

on:
  push:
    paths:
      - "Spring/**"
    branches: [ "main" ]

  workflow_dispatch:
    
permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working_directory: ./Spring

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Grant execute permission for gradlew & Build with Gradle
      run: |
        cd ${{ env.working_directory }}
        chmod +x ./gradlew
        ./gradlew clean build
